version: '3'
services:
  api:
    command: yarn run watch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - postgres-test
    environment:
      PORT: 3000
      JWT_AUDIENCE: "http://localhost:3000"
      JWT_ISSUER: "https://round-bread-5461.auth0.com/"
      JWKS_URI: "https://round-bread-5461.auth0.com/.well-known/jwks.json"
      POSTGRES_URI: "postgresql://postgres:ppmdevdb@postgres/postgres"
      POSTGRES_TEST_URI: "postgresql://postgres:ppmtestdb@postgres-test/postgres"
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ppmdevdb
  postgres-test:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ppmtestdb
